### ISSUE TITLE
CUDA Half errors

### ISSUE THREAD

**Issue by cdeterman** [RcppCore/RcppEigen#50] opened 2018-02-08 21:31 UTC
When I try to compile a file with `nvcc` that contains the Eigen headers I get the following errors

```
/usr/local/lib/R/site-library/RcppEigen/include/Eigen/src/Core/arch/CUDA/Half.h(96): error: identifier "x" is undefined

/usr/local/lib/R/site-library/RcppEigen/include/Eigen/src/Core/arch/CUDA/Half.h(138): error: identifier "x" is undefined

/usr/local/lib/R/site-library/RcppEigen/include/Eigen/src/Core/arch/CUDA/Half.h(138): error: class "Eigen::half" has no member "x"

/usr/local/lib/R/site-library/RcppEigen/include/Eigen/src/Core/arch/CUDA/Half.h(223): error: class "Eigen::half" has no member "x"

/usr/local/lib/R/site-library/RcppEigen/include/Eigen/src/Core/arch/CUDA/Half.h(223): error: class "Eigen::half" has no member "x"

/usr/local/lib/R/site-library/RcppEigen/include/Eigen/src/Core/arch/CUDA/Half.h(276): error: class "__half" has no member "x"

/usr/local/lib/R/site-library/RcppEigen/include/Eigen/src/Core/arch/CUDA/Half.h(372): error: class "Eigen::half" has no member "x"

/usr/local/lib/R/site-library/RcppEigen/include/Eigen/src/Core/arch/CUDA/Half.h(378): error: class "Eigen::half" has no member "x"

/usr/local/lib/R/site-library/RcppEigen/include/Eigen/src/Core/arch/CUDA/Half.h(387): error: class "Eigen::half" has no member "x"

/usr/local/lib/R/site-library/RcppEigen/include/Eigen/src/Core/arch/CUDA/Half.h(387): error: class "Eigen::half" has no member "x"

/usr/local/lib/R/site-library/RcppEigen/include/Eigen/src/Core/arch/CUDA/Half.h(571): error: class "Eigen::half" has no member "x"

/usr/local/lib/R/site-library/RcppEigen/include/Eigen/src/Core/arch/CUDA/Half.h(571): error: class "Eigen::half" has no member "x"

/usr/local/lib/R/site-library/RcppEigen/include/Eigen/src/Core/arch/CUDA/Half.h(603): error: class "Eigen::half" has no member "x"
```

Any insight to why this would be.  I thought CUDA 9.0 support was available as noted in this previous [pull request](https://bitbucket.org/eigen/eigen/pull-requests/327/cuda-90-support/diff).  I am using 9.1 at the moment.  Perhaps something between the source and this is different?

**Comment by eddelbuettel** [comment] 2018-02-08 21:32
Please:
- reproducible example
- how did you invoke it

etc pp.  The report is no use to any of us.  You could also have tested the PR before it got uploaded.

**Comment by eddelbuettel** [comment] 2018-02-08 21:37
There is some `#ifdef` magic in that file, and it looks like [the current repo master of that file](https://github.com/eigenteam/eigen-git-mirror/blob/master/Eigen/src/Core/arch/CUDA/Half.h) is similar so I suggest you seek help over with the Eigen team.

**Comment by yixuan** [comment] 2018-02-12 18:11
One more comment to @cdeterman : currently `RcppEigen` ships with the stable version of Eigen 3.3.x (the `3.3` branch), and the PR you mentioned was merged into the `default` branch, which has not been back-ported to `3.3` by the developers of Eigen. You can definitely report to Eigen to resolve this issue.

**Comment by eddelbuettel** [comment] 2018-11-24 15:58
We have done what we can here in 0.3.3.4.0 and again in 0.3.3.5.0. It really is an upstream issue you should take on there.

**Closed by eddelbuettel** 2018-11-24 15:58 UTC
