### ISSUE TITLE
Import Eigen 3.3.1

### ISSUE THREAD

**Issue by ChingChuan-Chen** [RcppCore/RcppEigen#40] opened 2017-01-20 14:29 UTC
Sorry for reckless PR to update the version of Eigen. Eigen 3.3.2 has been released two days ago, I try to update version of Eigen to 3.3.1.

I review the PR records, I find some patches before 3.2.9:
 * [patch 1](https://github.com/RcppCore/RcppEigen/blob/master/inst/include/Eigen/CholmodSupport#L9)
 * [patch 2](https://github.com/RcppCore/RcppEigen/blob/master/inst/include/unsupported/Eigen/src/SparseExtra/MatrixMarketIterator.h#L181-L183)
 * [patch 3](https://github.com/RcppCore/RcppEigen/pull/29/commits/6e45682336793e0adabf77d3028eb2d770bba8da) // It has been addressed by Eigen team.

But I don't know how to let RcppEigen not to use `long long int` which causes errors. 
I use `#define EIGEN_DEFAULT_DENSE_INDEX_TYPE long int`, but it is wrong.
After compiling several reverse dependent packages, I figure out that what Dirk says `#define` is wrong since  `EIGEN_DEFAULT_DENSE_INDEX_TYPE` has been defined in several packages.

**Comment by yixuan** [comment] 2017-01-20 18:48
Hi ChingChuan, could you provide an example where `long long int` causes errors? Since `RcppEigen` is an upstream package, it should not restrict `EIGEN_DEFAULT_DENSE_INDEX_TYPE` to be one specific type except for the default value defined by Eigen. And you are right, dependent packages are welcome to define their own `EIGEN_DEFAULT_DENSE_INDEX_TYPE` since it only affects one package.

**Comment by ChingChuan-Chen** [comment] 2017-01-20 18:55
In the Unit test, test.as.MSpMat, it will return the size of Sparse Matrix which is long long int and error occurs when compiling code with error: `library/Rcpp/include/Rcpp/internal/wrap.h:525:11: error: invalid conversion from 'long long int' to 'SEXP' [-fpermissive]`.

**Comment by eddelbuettel** [comment] 2017-01-20 19:11
Also, unless I am missing something, the standard trick to get `long long` is to just compile as C++11.

**Comment by yixuan** [comment] 2017-01-20 19:18
@ChingChuan-Chen 
Interestingly I didn't encounter the problem you mentioned. `EIGEN_DEFAULT_DENSE_INDEX_TYPE` by default is defined to be `std::ptrdiff_t`, not directly `long long int`. Whether `std::ptrdiff_t` is defined to be `long int` or `long long int` depends on the OS and compiler. Could you report your software environment?

**Comment by yixuan** [comment] 2017-01-20 19:27
And by the way, I have merged your PR to my branch (https://github.com/yixuan/RcppEigen/commits/Eigen3.3.2) prepared for Eigen 3.3.2, except for the new index definition. I'm now doing the reverse check, and we can have further discussions here.

**Comment by eddelbuettel** [comment] 2017-01-20 19:33
I am betting that @ChingChuan-Chen is on a 32-bit system (or maybe system with 32 and 64 bit).

**Comment by ChingChuan-Chen** [comment] 2017-01-20 19:38
I am on windows 64-bit with R x64 only.

**Comment by eddelbuettel** [comment] 2017-01-20 19:57
Strange.

**Comment by yixuan** [comment] 2017-01-20 20:01
Thanks. I've tried on Windows and yes the error occurs. The reason is documented here: http://eigen.tuxfamily.org/index.php?title=3.3#Index_typedef.

Basically the index type of sparse matrix was once defined to be `int` but now it is `std::ptrdiff_t`, and MinGW has some strange behaviors on `std::ptrdiff_t`.

My suggestion is that we change the unit test code to explicitly convert matrix sizes to `int`, and then use `Rcpp::wrap` to return them to R.

**Comment by ChingChuan-Chen** [comment] 2017-01-20 20:38
I find the following code in `Rtools\mingw_64\x86_64-w64-mingw32\include\stddef.h`

``` c++
#ifdef _WIN64
#define __PTRDIFF_TYPE__ long long int
#else
#define __PTRDIFF_TYPE__ long int
#endif
```

More oddly, another file in `Rtools\mingw_64\lib\gcc\x86_64-w64-mingw32\4.9.3\include\stddef.h` is

``` c++
#ifndef __PTRDIFF_TYPE__
#define __PTRDIFF_TYPE__ long int
#endif
typedef __PTRDIFF_TYPE__ ptrdiff_t;
```

It looks like R use the first definition for `std::ptrdiff_t` instead using the definition in `gcc-4.9.3`.

**Comment by ChingChuan-Chen** [comment] 2017-01-20 20:51
@yixuan
If we explicitly convert matrix sizes to `int` in examples, are there some packages also output the dimension of matrix. In my trial, not only the dimension of SparseMatrix is `long long int`, but also the dimension of DenseMatrix is.

**Comment by yixuan** [comment] 2017-01-20 20:55
You are right, basically we cannot rely on expressions like `Rcpp::wrap(mat.rows())`. I'll do a reverse search over those packages.

**Comment by eddelbuettel** [comment] 2017-01-20 21:02
```
R> library(Rcpp)
R> evalCpp("sizeof(std::ptrdiff_t)")
[1] 8
R> 
```

Can we map it to `double` ?

**Comment by yixuan** [comment] 2017-01-20 21:20
Do you mean something like this: https://github.com/yixuan/RcppEigen/commit/1c86f08beca1e8e89af256f5aba61ed103b72e71

**Comment by eddelbuettel** [comment] 2017-01-20 21:44
I think so. Converting to from 64-bit int to 32-bit is clearly lossy, sneaking by with double is a little dirty but possibly the best bet we have.

**Comment by ChingChuan-Chen** [comment] 2017-01-21 07:57
I have a question, does the vector and matrix class in RcppEigen wrap the dimension (`std::ptrdiff_s`) as `int`?

**Comment by eddelbuettel** [comment] 2017-01-21 14:09
This compiles just fine for me:

```c++
#include <RcppEigen.h>

// [[Rcpp::depends(RcppEigen)]]

// [[Rcpp::export]]
int showDim(Eigen::MatrixXd m) {
    Rcpp::Rcout << "Rows " << m.rows() << std::endl;
    Rcpp::Rcout << "Cols " << m.cols() << std::endl;
    return m.rows();
}

/*** R
showDim(matrix(1:9,3,3))
*/
```

and I get

```r
R> Rcpp::sourceCpp('/tmp/eigenmat.cpp')

R> showDim(matrix(1:9,3,3))
Rows 3
Cols 3
[1] 3
R> 
```

What errror are you seeing on dimensions?

**Comment by ChingChuan-Chen** [comment] 2017-01-21 14:22
If I use `wrap(m.rows()`, there is a compiling error:

``` text
C:/R/MRO-3.3.1/library/Rcpp/include/Rcpp/internal/wrap.h:525:11: error: invalid conversion from 'long long int' to 'SEXP' [-fpermissive]
  SEXP x = object ;
```

In that case, if someone may use `Rcpp::List` to output the dimension of matrix, it will get same error as mine.

``` c++
Rcpp::List(Rcpp::_["row"] = m.rows(), Rcpp::_["columns"} = m.cols())
```

So we cannot rely on expressions like `Rcpp::wrap(mat.rows())` like @yixuan say.

**Comment by eddelbuettel** [comment] 2017-01-21 14:31
Why would you wrap `m.rows()`? What is the point? 

I just showed you that the `int` flows through automagically.

**Comment by eddelbuettel** [comment] 2017-01-21 14:35
This works just fine, why would you not use something like this:

```c++
// [[Rcpp::export]]
Rcpp::IntegerVector getDims(Eigen::MatrixXd m) {
    return Rcpp::IntegerVector::create(m.rows(), m.cols());
}
```

I am getting the impression that you are not all that familiar with either Rcpp or RcppEigen.  I really appreciate that you want to help.  But may I ask that we stop repeating unsubstantiated stories about non-bugs _in the thread about upgrading to RcppEigen to 3.3_ ?

**Comment by yixuan** [comment] 2017-01-21 14:39
Below is a summary of what we discuss here to avoid some confusion.

1. `Eigen` dense matrices use `std::ptrdiff_t` as type for index. `Eigen` sparse matrices use `int` to index on 3.2.x, and use `std::ptrdiff_t` on Eigen 3.3.y.
2. MinGW for Windows x64 defines `std::ptrdiff_t` to be `long long int`, which is not **directly** understood by `Rcpp::wrap`. I guess other compilers/OS will define `std::ptrdiff_t` as `long int`, so Dirk does not reproduce the error.

**Comment by ChingChuan-Chen** [comment] 2017-01-21 14:40
Sorry, I just want to be lazy for using `warp`, not from explicitly conversion of `long long int`. 
We can just going on upgrading to RcppEigen to 3.3.

**Comment by eddelbuettel** [comment] 2017-01-21 14:46
Please demonstrate that `long long int` _also fails when compiled as C++11_.  That is the point I have been making for a while, but I don't seem to get through.

(It is also a sore issue for Rcpp since the start as R Core insists on C++98 which does not have it. C++0x and C++11 both overcome this.)

**Comment by ChingChuan-Chen** [comment] 2017-01-21 14:48
Compiled as C++11 works on windows x64.

**Comment by eddelbuettel** [comment] 2017-01-21 14:48
Also: @ChingChuan-Chen please start to support claims by reproducible examples.  Everything else is wasting my time.

**Comment by eddelbuettel** [comment] 2017-01-21 14:48
> Compiled as C++11 works on windows x64.

Thank you. Only took us two days to get here.

**Comment by yixuan** [comment] 2017-01-21 14:53
It's good to see that we've reached an agreement. I've tested the dependent packages and there are still a few failures, either due to regressions in Eigen 3.3 or the packages themselves. I will open another issue to list those failed examples.

**Closed** 2017-04-28 17:41 UTC
